#!/usr/bin/env python3

import gnupg
import json
import tempfile

# Parameters
gnupghome = tempfile.mkdtemp()
gpg = gnupg.GPG(gnupghome=gnupghome)

# Generate key and import it
passphrase="doYouEvenPassphrase"
key_input_data = gpg.gen_key_input(
    key_length=2048,
    name_real="TEMPORARY ansible-sign TEST key",
    name_comment="Generated by ansible-sign test fixture",
    name_email="foo@example.com",
    passphrase=passphrase,
    no_protection=False,
)
key = gpg.gen_key(key_input_data)

# Set output dict
output = {}
output['public_key'] = gpg.export_keys(key.fingerprint)
output['secret_key'] = gpg.export_keys(key.fingerprint, secret=True, passphrase="doYouEvenPassphrase")
output['passphrase'] = passphrase
output['fingerprint'] = key.fingerprint

# Print output as json
output_json = json.dumps(output)
print(output_json)
