---

- name: Run Async Tasks playbooks
  hosts: all
  gather_facts: true
  tasks:

  - name: Create the async directory to prevent race conditions
    file:
      path: ~/.ansible_async
      state: directory

  - name: Poll a sleep
    command: "sleep 10"
    async: 30
    poll: 5

  - debug:
      msg: "I'm a debug message."

  - name: Fire and forget a slow command
    command: "sleep 15 && touch /tmp/test_file"
    async: 30
    poll: 5
    register: fired

  - debug:
      msg: "I'm another debug message."

  - name: Examine slow command
    async_status:
      jid: "{{ fired.ansible_job_id }}"
      mode: status
    register: slow_command
    until: slow_command.finished
    retries: 20

  - name: Fire and forget a slow reversal
    command: "sleep 10 && rm -f /tmp/test_file"
    async: 30
    poll: 5
    register: fired

  - debug:
      msg: "I'm yet another debug message."

  - name: Examine slow reversal
    async_status:
      jid: "{{ fired.ansible_job_id }}"
      mode: status
    register: slow_command
    until: slow_command.finished
    retries: 20
