---

- hosts: all
  gather_facts: false
  tasks:

  - name: Create the async directory to prevent race conditions
    file:
      path: ~/.ansible_async
      state: directory
    run_once: true

  - name: Poll a sleep
    shell: "sleep 10"
    async: 30
    poll: 5

  - debug:
      msg: "I'm a debug message."

  - name: Fire and forget a slow command
    shell: |
      sleep 15
      touch /tmp/test_file
    async: 30
    poll: 0
    register: fired

  - debug:
      msg: "I'm another debug message."

  - name: Examine slow command
    async_status: jid={{ fired.ansible_job_id }}
    register: slow_command
    until: slow_command.finished
    retries: 20

  - name: Fire and forget a slow reversal
    shell: |
      sleep 10
      rm -f /tmp/test_file
    async: 30
    poll: 0
    register: fired

  - debug:
      msg: "I'm yet another debug message."

  - name: Examine slow reversal
    async_status: jid={{ fired.ansible_job_id }}
    register: slow_command
    until: slow_command.finished
    retries: 20
