---

- hosts: all
  gather_facts: false
  connection: local
  vars:
    num_messages: 50
  tasks:
    - debug:
        msg: "This is a debug message: {{ item }}"
      with_sequence: 'count={{ num_messages }}'

    - debug:
        msg: last message before a pause
      run_once: true

    - pause:
        seconds: 5

    - debug:
        msg: "This is a debug message: {{ item }}"
      with_sequence: 'count={{ num_messages }}'

    - debug:
        msg: last message before then end
      run_once: true
