---
- hosts: all
  gather_facts: no
  vars:
    message_size: "{{ message_size|default(1024)|int }}" # message size in Bytes[1KB]
    num_messages: 10  #number of messages
    chatty_message: "{{ ['$'] * message_size | join('') }}"
  tasks:
    - debug:
          msg: "{{ chatty_message }}"
      with_sequence: "count={{ num_messages }}"
