- name: test playbooks that utilize ansible-specific json data types
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: include extra vars with vault/unsafe tags
      include_vars: custom_json_vars.yml
    - debug: msg="{{ vaulted_text }}"
    - debug: msg="{{ unsafe_text }}"
    - debug: msg="{{ datetime_text }}"
