---
- hosts: all
  connection: local
  gather_facts: false
  vars:
    default_var: foobar
    var_name: default_var
    leading_text: "specified_var_is:"
  tasks:
    - name: Print value of variable specified by var_name contents
      debug: msg="{{ leading_text }}{{ lookup('vars', var_name) }}"
