---

- hosts: all
  gather_facts: true
  tasks:
    - name: set a fact man
      set_fact:
        foo: "bar"
        bar:
          a:
            b:
              - "c"
              - "d"
        cacheable: "{{ set_fact_cacheable | default(false) }}"
    - name: set some stats man
      set_stats:
        data:
          string: 'abc'
          integer: 123
          float: 1.0
          unicode: '竳䙭韽'
          boolean: true
          none: null
          list:
            - 'abc'
            - 123
            - 1.0
            - '竳䙭韽'
            - true
            - null
            - []
            - {}
          object:
            string: 'abc'
            integer: 123
            float: 1.0
            unicode: '竳䙭韽'
            boolean: true
            none: null
            list: []
            object: {}
          empty_list: []
          empty_object: {}
      no_log: "{{ artifact_no_log | default(false) }}"
