---
- hosts: all
  gather_facts: false
  tasks:
    - name: task with status "changed"
      command: /bin/true
      changed_when: true
      notify: handler
  handlers:
    - name: handler
      command: /bin/true
