---

- name: 'Test playbook to read the content from a file'
  hosts: all
  gather_facts: false

  tasks:

    - name: "Get {{ filepath }} content"
      command: "cat {{ filepath }}"
      register: cnt

    - name: "Check if {{ filepath }} content is correct"
      fail:
        msg: "{{ filepath }} doesnt have the correct content"
      when: "not '{{ cnt_to_check }}' in cnt"