--- #Removing users by a loop
- hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - user: name={{ item }} state=absent remove=yes
    with_items:
      - user1
      - user2
      - user3
...