---

- name: 'Test playbook to sleep for a specified interval'
  hosts: all
  gather_facts: false
  vars:
    sleep_interval: 1000000

  tasks:
    - name: sleep for a specified interval
      command: sleep '{{ sleep_interval }}'
