---
- name: Verify that ansible can correctly pass arguments to ansible in shell
  hosts: all
  gather_facts: False
  tasks:
    - name: Write inventory file
      blockinfile:
        path: '/tmp/inventory.ansible.shell'
        block: |
          localhost ansible_connection=local
        state: present
        create: True

    - name: Run Playbook
      shell: "ANSIBLE_NOCOLOR=1 ansible-playbook -i '/tmp/inventory.ansible.shell' ./ping.yml"
