---
- hosts: localhost
  vars:
    set_stats_data:
      string: 'abc'
      integer: 123
      float: 1.0
      unicode: '竳䙭韽'
      boolean: true
      none: null
      list:
        - 'abc'
        - 123
        - 1.0
        - '竳䙭韽'
        - true
        - null
        - []
        - {}
      object:
        string: 'abc'
        integer: 123
        float: 1.0
        unicode: '竳䙭韽'
        boolean: true
        none: null            
        list: []
        object: {}
      empty_list: []
      empty_object: {}
    fail_at_end: false
  tasks:
  - set_stats:
      data: "{{ set_stats_data }}"
  - fail: "Intentionally failing because variable 'fail_at_end' was set to {{ fail_at_end }}"
    when: fail_at_end
