---
- hosts: localhost
  tasks:
  - set_stats:
      data:
        string: 'abc'
        integer: 123
        float: 1.0
        unicode: '竳䙭韽'
        boolean: true
        none: null
        list:
          - 'abc'
          - 123
          - 1.0
          - ''
          - true
          - null
          - []
          - {}
        object:
          string: 'abc'
          integer: 123
          float: 1.0
          unicode: '竳䙭韽'
          boolean: true
          none: null            
          list: []
          object: {}
        empty_list: []
        empty_object: {} 
