---
- name: basic windows
  hosts: all
  gather_facts: false
  tasks:

  - name: password echo
    debug:
      var: ansible_password

  - name: ping
    ansible.windows.win_ping:

  - ansible.windows.win_powershell:
      script: | 
        Write-Host "Hello World!"

  - name: test stat module on file
    win_stat: path="C:/Windows/win.ini"
    register: stat_file

  - debug: var=stat_file

  - name: check stat_file result
    assert:
        that:
           - "stat_file.stat.exists"
           - "not stat_file.stat.isdir"
           - "stat_file.stat.size > 0"
