---

- name: 'Test playbook to write content into a file'
  hosts: all
  gather_facts: false

  tasks:

    - name: "Write content into a file"
      copy:
        dest: "{{ filepath }}"
        content: "Test Line"

    - name: "Check file {{ filepath }} stat result"
      stat:
        path: "{{ filepath }}"
      register: st

    - name: "Check if file {{ filepath }} exists"
      fail:
        msg: "{{ filepath }} doesnt exist"
      when: not st.stat.exists | bool

    - name: "Get {{ filepath }} content"
      command: "cat {{ filepath }}"
      register: cnt

    - name: "Check if {{ filepath }} content is correct"
      lineinfile:
        dest: "{{ filepath }}"
        line: "Test Line"
      check_mode: yes
      register: present
      failed_when: present.changed