---

- hosts: all
  gather_facts: false
  vars:
    num_messages: 50
    num_changed: 50
    num_failed: 50
  tasks:
    - debug:
        msg: "This is a debug message: {{ item }}"
      with_sequence: 'count={{ num_messages }}'

    - include_tasks: changed.yml
      with_sequence: 'count={{ num_changed }}'

    - debug:
        msg: "This is a debug message that fails: {{ item }}"
      failed_when: true

    # BUG: this is not working in AWX
    # - include_tasks: failed.yml
    #   with_sequence: 'count={{ num_changed }}'
