- name: Fetch project_base_dir
  uri:
    url: "{{ lookup('env', 'TOWER_HOST') }}/api/v2/config/"
    user: "{{ lookup('env', 'TOWER_USERNAME') }}"
    password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    validate_certs: false
    return_content: true
    force_basic_auth: true
  register: awx_config

- tower_inventory:
    name: localhost
    organization: Default

- tower_host:
    name: localhost
    inventory: localhost
    variables:
      ansible_connection: local

- name: create an unused SSH / Machine credential
  tower_credential:
    name: dummy
    kind: ssh
    ssh_key_data: |
      -----BEGIN EC PRIVATE KEY-----
      MHcCAQEEIIUl6R1xgzR6siIUArz4XBPtGZ09aetma2eWf1v3uYymoAoGCCqGSM49
      AwEHoUQDQgAENJNjgeZDAh/+BY860s0yqrLDprXJflY0GvHIr7lX3ieCtrzOMCVU
      QWzw35pc5tvuP34SSi0ZE1E+7cVMDDOF3w==
      -----END EC PRIVATE KEY-----
    organization: Default

- name: Disable bubblewrap
  command: tower-cli setting modify AWX_PROOT_ENABLED false

- block:
    - name: Create a directory for manual project
      vars:
        project_base_dir: "{{ awx_config.json.project_base_dir }}"
      command: tower-cli ad_hoc launch --wait --inventory localhost
        --credential dummy --module-name shell
        --module-args "mkdir -p {{ project_base_dir }}/{{ project_dir_name }} || true"
  always:
    - name: enable bubblewrap
      command: tower-cli setting modify AWX_PROOT_ENABLED true
