---
# Basic rulebook with job template, 
# it will run a job template against single host in the inventory
# incase of the payload ke of letters is equle to "aaa"
- name: Basic short
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 5000
  rules:
    - name: Run job template when the event is aaa
      condition: event.payload.letters== "aaa"
      actions:
        - run_job_template:
            organization: Default
            name: run_basic
            job_args:
              limit: "{{ event.payload.meta.hosts }}"
              extra_vars:
                pause_time_min: 5

        - debug:
            msg: "Basic short rulebook, event {{ event }}"

  execution_strategy: "parallel"
