---
- name: Test run workflow templates
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
        delay: 10
  rules:
    - name: "Run workflow template"
      condition: event.i == 0
      action:
        run_workflow_template:
          name: workflow_basic
          job_args:
            extra_vars:
              fake_execution_time: "2"
          retries: 1
          delay: 10
          organization: Default
