---
- name: Match multiple rules
  match_multiple_rules: true
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: r1
      condition: event.i == 0
      action:
        print_event:
    - name: r2
      condition: event.i == 0 
      action:
        debug:
    - name: r3
      condition: event.i == 0
      action:
        debug:
