---
- name: Mutliple rules fired for single fact
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: Say Hello
      condition: event.i == 0
      action:
        set_fact:
          fact:
             j: 42 
    - name: fact_rule1
      condition: fact.j == 42 
      action:
        print_event:
    - name: fact_rule2
      condition: fact.j == 42 
      action:
        debug:
