---
- name: Run a webhook listener service
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 5000
  rules:
    - name: Webhook event
      condition: event.payload.ping == "pong"
      action:
        debug:
          msg: "Webhook triggered!"

    - name: Shutdown
      condition: event.payload.shutdown is defined
      action:
        shutdown:
