---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    state: "absent"
    zone: "us-east1-b"
    region: "us-east1"
    allow_errors: False
  tasks:
    - gcp_compute_instance:
        name: "this-is-an-instance-created-by-tower-qa-tests"  # should not match anything
        state: "{{ state }}"
        zone: us-east1-d
        auth_kind: serviceaccount
      ignore_errors: "{{ allow_errors | bool }}"
    - gcp_storage_bucket:
        name: "qe-storage-bucket"
        state: "{{ state }}"
      ignore_errors: "{{ allow_errors | bool }}"
    - gcp_compute_network:
        name: "qe-network-instance"
        state: "{{ state }}"
      ignore_errors: "{{ allow_errors | bool }}"
    - gcp_compute_instance:
        name: "qe-compute-instance"
        state: "{{ state  }}"
        zone: "{{ zone  }}"
      ignore_errors: "{{ allow_errors | bool }}"
    - gcp_compute_address:
        name: "qe-compute-address"
        state: "{{ state }}"
        region: "{{ region }}"
      ignore_errors: "{{ allow_errors | bool }}"
    - gcp_compute_disk:
        name: "qe-compute-address"
        state: "{{ state }}"
        zone: "{{ zone }}"
      ignore_errors: "{{ allow_errors | bool }}"
