---
authors:
  - AWX Project Contributors <awx-project@googlegroups.com>
dependencies: {}
description: >-
  External query testing collection. No embedded query file.
  Not for use in production.
documentation: https://github.com/ansible/awx
homepage: https://github.com/ansible/awx
issues: https://github.com/ansible/awx
license:
  - GPL-3.0-or-later
name: external
namespace: demo
readme: README.md
repository: https://github.com/ansible/awx
tags:
  - demo
  - testing
  - external_query
version: 3.0.0
