---
authors:
  - AWX Project Contributors <awx-project@googlegroups.com>
dependencies: {}
description: >-
  Query testing collection with embedded query file.
  Not for use in production.
documentation: https://github.com/ansible/awx
homepage: https://github.com/ansible/awx
issues: https://github.com/ansible/awx
license:
  - GPL-3.0-or-later
name: query
namespace: demo
readme: README.md
repository: https://github.com/ansible/awx
tags:
  - demo
  - testing
  - query
version: 0.0.1
