---
- name: Test that wrong source fails
  hosts: all
  sources:
    - ansible.eda.idonotexist:
        limit: 6
  rules:
    - name: Run job template
      condition: event.i == 1
      action:
        run_job_template:
          name: Hello World
          organization: Default
          job_args:
            extra_vars:
              hello: Fred
    - name: Debug
      condition: event.i == 2
      action:
        debug: